package constants

const (
	TRANSACTION_CODE_TRIGGER_DEBIT          = 1
	TRANSACTION_CODE_TRIGGER_CREDIT         = 2
	TRANSACTION_CODE_TRIGGER_DEBIT_REVERSAL = 3
	TRANSACTION_CODE_TRIGGER_DEBIT_REFUND   = 4
	TRANSACTION_CODE_TRANSFER_INTRABANK     = 5

	LATEST_TRX_SUCCESS = 1
	LATEST_TRX_PENDING = 2
	LATEST_TRX_FAILED  = 3

	LATEST_TRX_SUCCESS_DESC = "Success"
	LATEST_TRX_PENDING_DESC = "Pending"
	LATEST_TRX_FAILED_DESC  = "Failed"
)
