package constants

const (
	// CIF Type
	CIF_TYPE_PERSONAL  = 1
	CIF_TYPE_CORPORATE = 2

	// CIF Type Description
	CIF_TYPE_DESC_PERSONAL  = "PERSONAL"
	CIF_TYPE_DESC_CORPORATE = "CORPORATE"

	// Identity Type
	CIF_IDENTITY_TYPE_KTP      = "KTP"
	CIF_IDENTITY_TYPE_PHONE    = "PHONE"
	CIF_IDENTITY_TYPE_PASSPORT = "PASSPORT"
	CIF_IDENTITY_TYPE_NPWP     = "NPWP"

	// Citizenship
	CIF_CITIZENSHIP_WNI = "WNI"
	CIF_CITIZENSHIP_WNA = "WNA"
)

var (
	CIF_IDENTITY_TYPE_POOL = []string{
		CIF_IDENTITY_TYPE_KTP,
		CIF_IDENTITY_TYPE_PHONE,
		CIF_IDENTITY_TYPE_PASSPORT,
		CIF_IDENTITY_TYPE_NPWP,
	}
)
