package constants

const (
	DEPOSITO_TYPE_FIXED    = "FIXED"
	DEPOSITO_TYPE_FLOATING = "FLOATING"

	DEPOSITO_TERM_DAILY     = "DAILY"
	DEPOSITO_TERM_MONTHLY   = "MONTHLY"
	DEPOSITO_TERM_ANNUALY   = "ANNUALY"
	DEPOSITO_TERM_ON_DEMAND = "ON_DEMAND"

	DEPOSITO_RATE_TYPE_NONE               = "NONE"
	DEPOSITO_RATE_TYPE_FIXED              = "FIXED"
	DEPOSITO_RATE_TYPE_PRECENTAGE_ANNUALY = "PERCENTAGE_ANNUALY"
	DEPOSITO_RATE_TYPE_PRECENTAGE_TOTAL   = "PERCENTAGE_TOTAL"

	DEPOSITO_PENALTY_NO              = 0
	DEPOSITO_PENALTY_YES             = 1
	DEPOSITO_PENALTY_TYPE_NONE       = "NONE"
	DEPOSITO_PENALTY_TYPE_FIXED      = "FIXED"
	DEPOSITO_PENALTY_TYPE_PERCENTAGE = "PERCENTAGE"

	DEPOSITO_TAX_NO              = 0
	DEPOSITO_TAX_YES             = 1
	DEPOSITO_TAX_TYPE_NONE       = "NONE"
	DEPOSITO_TAX_TYPE_FIXED      = "FIXED"
	DEPOSITO_TAX_TYPE_PERCENTAGE = "PERCENTAGE"

	DEPOSITO_STATUS_ACTIVE    = "ACTIVE"
	DEPOSITO_STATUS_FREEZE    = "FREEZE"
	DEPOSITO_STATUS_WITHDRAWN = "WITHDRAWN"

	DEPOSITO_PRODUCT_STATUS_ACTIVE  = "ACTIVE"
	DEPOSITO_PRODUCT_STATUS_CLOSED  = "CLOSED"
	DEPOSITO_PRODUCT_STATUS_EXPIRED = "EXPIRED"
)
