package constants

const (
	// Saving Type ID
	SAVING_TYPE_ID_SAVING  = 1
	SAVING_TYPE_ID_DEPOSIT = 2
	SAVING_TYPE_ID_BINA    = 3

	// Saving Type Code
	SAVING_TYPE_CODE_SAVING  = "001"
	SAVING_TYPE_CODE_DEPOSIT = "002"
	SAVING_TYPE_CODE_BINA    = "003"

	// Saving Type Name
	SAVING_TYPE_NAME_SAVING  = "SAVING"
	SAVING_TYPE_NAME_DEPOSIT = "DEPOSIT"
	SAVING_TYPE_NAME_BINA    = "SAVING BINA"

	// Saving Bina
	SAVING_BINA_CODE = "513"
)
