package constants

const (
	LINKED_STATUS_INQUIRIES = "INQUIRY"
	LINKED_STATUS_LINKED    = "LINKED"
	LINKED_STATUS_UNLINK    = "UNLINKED"

	SAVING_ACCOUNT_STATUS_ACTIVE      = "ACTIVE"
	SAVING_ACCOUNT_STATUS_ACTIVE_DESC = "Aktif"

	SAVING_ACCOUNT_STATUS_UNVERIFIED      = "UNVERIFIED"
	SAVING_ACCOUNT_STATUS_UNVERIFIED_DESC = "Belum verifikasi"

	SAVING_ACCOUNT_STATUS_BLOCKER_PIN      = "BLOCKER_PIN"
	SAVING_ACCOUNT_STATUS_BLOCKER_PIN_DESC = "Autentikasi gagal, akun diblokir"

	SAVING_ACCOUNT_STATUS_CLOSED      = "CLOSED"
	SAVING_ACCOUNT_STATUS_CLOSED_DESC = "Ditutup"

	// STATUS UPGRADE ACCOUNT
	UPGRADE_ACCOUNT_STATUS_WAITING  = "WAITING"
	UPGRADE_ACCOUNT_STATUS_SUCCESS  = "SUCCESS"
	UPGRADE_ACCOUNT_STATUS_REJECTED = "REJECTED"
	UPGRADE_ACCOUNT_STATUS_FAILED   = "FAILED"

	APPROVAL_REMARKS_WAITING_FOR_APPROVAL = "Menunggu Persetujuan"
)
