version: '3'
services:
  dps-scanner-maj:
    image: ${REGISTRY_URL}/${APP_NAME}:${APP_VERSION}
    build: "./"
    container_name: dps-scanner-maj
    restart: unless-stopped
    tty: true
    environment:
      TZ: "Asia/Jakarta"

    volumes:
      - ./layout.json:/app/layout.json
      - ./static:/static

    ports:
      - "10124:8080"
    logging:
      driver: "json-file"
      options:
        max-size: "1000m"
    networks:
      - sample-service-network
networks:
  sample-service-network:
    driver: bridge
